version: '3'
services:
  vector-server:
    image: timberio/vector:0.34.0-debian
    volumes:
      - ./conf/vector-server:/etc/vector
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - share:/logs
  vector-agent:
    image: timberio/vector:0.34.0-debian
    volumes:
      - ./conf/vector-agent:/etc/vector
      - share:/logs
volumes:
  share: